version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Instivo123#
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: instivo-app
    ports:
      - "8085:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:Instivo123#@mongo:27017/instivotesting_db?authSource=admin

volumes:
  mongo-data:
